import 'package:flutter/material.dart';

class CommonSnackBar extends SnackBar {
  CommonSnackBar({
    super.key,
    required ThemeData theme,
    required String text,

    /// Function to run when (autogenerated) Undo button is pressed. Pass null/don't pass a value to omit the Undo button
    void Function()? onUndoPressed,
  }) : super(
         backgroundColor: theme.colorScheme.surface,
         content: ListTile(
           minTileHeight: 24,
           contentPadding: EdgeInsets.zero,
           leading: Text(text, style: theme.textTheme.bodyLarge),
           trailing:
               onUndoPressed == null
                   ? null
                   : TextButton(
                     onPressed: onUndoPressed,
                     child: Text(
                       'Undo',
                       style: theme.textTheme.bodyLarge?.copyWith(
                         color: theme.colorScheme.primary,
                       ),
                     ),
                   ),
         ),
       );

  void show(BuildContext context) =>
      ScaffoldMessenger.of(context)
        ..hideCurrentSnackBar()
        ..showSnackBar(this);
}
